### ISSUE TITLE
Sift.pics android app's translations to Transifex

### ISSUE THREAD

**Issue by puik** [Ajapaik/sift-pics-android#2]
Currently we do not have Sift.pics' android app's translations on Transifex as before we hosted the code on a private repo at Bitbucket and did the translations there.
@Lauriy @Abbe98 how could we get the app's translations to Transifex?

**Comment by Abbe98** [comment]
Seams to be done?

**Comment by puik** [comment]
Yes, @Lauriy solved that
@Abbe98, I added you as collaborator to the project and described another issue.
Do you use gitter-chat? Or should we create a skype group maybe?

**Comment by Abbe98** [comment]
I use Gitter, not using Skype so much nowadays...

I translated the app to Swedish but left two strings as I'm not sure about what they really means in the context.

**Comment by puik** [comment]
I created a gitter chat for Sift.pics and invited you.
Maybe it's easier to discuss there.
Actually I now remember we also have a category pair we do not actually use (public/private). Was that the one?

**Comment by Abbe98** [comment]
No it was not.
